services:
  notion-document-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notion-document-store
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NOTION_INTERNAL_INTEGRATION_SECRET=${NOTION_INTERNAL_INTEGRATION_SECRET}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_API_VERSION=${NOTION_API_VERSION:-2022-06-28}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DOCKER_CONTAINER=true
    
    # Port mappings
    ports:
      - "3000:3000"  # MCP SSE endpoint
      - "8080:8080"  # Health check endpoint
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Security
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/logs:noexec,nosuid,size=50m
      - /home/mcpuser/.cache:noexec,nosuid,size=100m
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Networks
    networks:
      - notion-mcp

  # Optional: Monitoring with Prometheus (for production)
  prometheus:
    image: prom/prometheus:latest
    container_name: notion-mcp-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - notion-mcp
    profiles:
      - monitoring

networks:
  notion-mcp:
    driver: bridge
    name: notion-mcp-network

# Volumes for persistent data (if needed in future)
volumes:
  prometheus_data:
    driver: local